# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: cmake install
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz
        tar -zxvf cmake-3.15.2.tar.gz
        cd cmake-3.15.2
        ./bootstrap
        cd ..
    - name: Install dependencies
      run: |
        
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install fastapi 
        pip install "uvicorn[standard]"
        pip install chromadb
        pip install langchain
        pip install langchain_community
        pip install sentence-transformers
        pip install llama-cpp-python
        pip install pandas
        pip install unstructured
        pip install openpyxl
        pip install googletrans==3.1.0a0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: FastApi
      run: |
        uvicorn srv:app --reload
